version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    image: sand050965/hand-tracking-canvas
    container_name: app
    ports:
      - "3000:3000"
    restart: on-failure
